apiVersion: v1
kind: Service
metadata:
  name: nginx-volume
spec:
  type: LoadBalancer
  selector:
    app: nginx-volume
  ports:
  - port: 8000
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-volume
  template:
    metadata:
      labels:
        app: nginx-volume
    spec:
      containers:
      - name: nginx-volume
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-html
        # hostPath only exists in single-node cluster
        # see https://kubernetes.io/docs/concepts/storage/volumes/#types-of-volumes for other volume types
        hostPath:
          # folder must exist
          path: /C/temp/nginx-html # mac: /tmp/nginx-html
